name: PR Test
on:
  pull_request:
    types: [ assigned, labeled, opened, edited, reopened, synchronize, ready_for_review, review_requested, review_request_removed, unlocked ]
        
jobs:
  deploy:
    if: ${{ github.event.label.name == 'to test' }}
    name: PR Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Node $
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install and npm run build
        run: |
          npm ci
          npm run build